version: "2"

linters:
  default: none
  enable:
    - floatmoney

  settings:
    custom:
      floatmoney:
        type: "module"
        settings:
          names:
            - Amount
            - Balance
            - Currency
            - Money